/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const FlexRender: typeof import('@tanstack/vue-table').FlexRender
  const RouterLink: typeof import('vue-router').RouterLink
  const VAT_RATE: typeof import('./src/utils/tabCalculations').VAT_RATE
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const addTabItemQuery: typeof import('./src/services/supabase/queries/tabQueries').addTabItemQuery
  const barApi: typeof import('./src/services/api/barApi').default
  const barByIdQuery: typeof import('./src/services/supabase/queries/barQueries').barByIdQuery
  const barQuery: typeof import('./src/services/supabase/queries/barQueries').barQuery
  const barsQuery: typeof import('./src/services/supabase/queries/barQueries').barsQuery
  const calculateTabTotals: typeof import('./src/utils/tabCalculations').calculateTabTotals
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createTabPaymentQuery: typeof import('./src/services/supabase/queries/tabQueries').createTabPaymentQuery
  const createTabQuery: typeof import('./src/services/supabase/queries/tabQueries').createTabQuery
  const createTabSplitQuery: typeof import('./src/services/supabase/queries/tabQueries').createTabSplitQuery
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const deleteDrinkQuery: typeof import('./src/services/supabase/queries/drinkQueries').deleteDrinkQuery
  const deleteTabItemQuery: typeof import('./src/services/supabase/queries/tabQueries').deleteTabItemQuery
  const deleteTabSplitQuery: typeof import('./src/services/supabase/queries/tabQueries').deleteTabSplitQuery
  const drinkApi: typeof import('./src/services/api/drinkApi').default
  const drinkQuery: typeof import('./src/services/supabase/queries/drinkQueries').drinkQuery
  const drinksByCategoryQuery: typeof import('./src/services/supabase/queries/drinkQueries').drinksByCategoryQuery
  const drinksQuery: typeof import('./src/services/supabase/queries/drinkQueries').drinksQuery
  const effectScope: typeof import('vue').effectScope
  const fetchDrinks: typeof import('./src/services/supabase/queries/drinkQueries').fetchDrinks
  const formatCurrency: typeof import('./src/utils/currency').formatCurrency
  const getCoreRowModel: typeof import('@tanstack/vue-table').getCoreRowModel
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getPaginationRowModel: typeof import('@tanstack/vue-table').getPaginationRowModel
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const menuApi: typeof import('./src/services/api/menuApi').default
  const menuKey: typeof import('./src/providers/injectionKeys').menuKey
  const menuQuery: typeof import('./src/services/supabase/queries/menuQueries').menuQuery
  const menusQuery: typeof import('./src/services/supabase/queries/menuQueries').menusQuery
  const menusWithCategoriesQuery: typeof import('./src/services/supabase/queries/menuQueries').menusWithCategoriesQuery
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const openTabsQuery: typeof import('./src/services/supabase/queries/tabQueries').openTabsQuery
  const profileApi: typeof import('./src/services/api/profileApi').default
  const profileQuery: typeof import('./src/services/supabase/queries/profileQueries').profileQuery
  const profilesQuery: typeof import('./src/services/supabase/queries/profileQueries').profilesQuery
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const socket: typeof import('./src/services/socket/socket').socket
  const storeToRefs: typeof import('pinia').storeToRefs
  const supabase: typeof import('./src/providers/supabaseClient').supabase
  const tabApi: typeof import('./src/services/api/tabApi').default
  const tabItemsQuery: typeof import('./src/services/supabase/queries/tabQueries').tabItemsQuery
  const tabPaymentsQuery: typeof import('./src/services/supabase/queries/tabQueries').tabPaymentsQuery
  const tabQuery: typeof import('./src/services/supabase/queries/tabQueries').tabQuery
  const tabSplitsQuery: typeof import('./src/services/supabase/queries/tabQueries').tabSplitsQuery
  const tabTotalsQuery: typeof import('./src/services/supabase/queries/tabQueries').tabTotalsQuery
  const tabsQuery: typeof import('./src/services/supabase/queries/tabQueries').tabsQuery
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const todaysTabsCountQuery: typeof import('./src/services/supabase/queries/tabQueries').todaysTabsCountQuery
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const updateDrinkQuery: typeof import('./src/services/supabase/queries/drinkQueries').updateDrinkQuery
  const updateTabItemQuery: typeof import('./src/services/supabase/queries/tabQueries').updateTabItemQuery
  const updateTabQuery: typeof import('./src/services/supabase/queries/tabQueries').updateTabQuery
  const updateTabSplitQuery: typeof import('./src/services/supabase/queries/tabQueries').updateTabSplitQuery
  const updateUserQuery: typeof import('./src/services/supabase/queries/profileQueries').updateUserQuery
  const useAddToTabStore: typeof import('./src/stores/ui/addToTab').useAddToTabStore
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./src/stores/auth').useAuthStore
  const useBarsStore: typeof import('./src/stores/loaders/bars').useBarsStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDrinkSheetStore: typeof import('./src/stores/ui/drinkSheet').useDrinkSheetStore
  const useDrinksStore: typeof import('./src/stores/loaders/drinks').useDrinksStore
  const useErrorStore: typeof import('./src/stores/error').useErrorStore
  const useId: typeof import('vue').useId
  const useMemoize: typeof import('@vueuse/core').useMemoize
  const useMenusStore: typeof import('./src/stores/loaders/menus').useMenusStore
  const useMeta: typeof import('vue-meta').useMeta
  const useModel: typeof import('vue').useModel
  const useNewTabSheetStore: typeof import('./src/stores/ui/newTabSheet').useNewTabSheetStore
  const usePageStore: typeof import('./src/stores/page').usePageStore
  const usePaginationStore: typeof import('./src/stores/ui/pagination').usePaginationStore
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useSplitBillSheetStore: typeof import('./src/stores/ui/splitBillSheet').useSplitBillSheetStore
  const useTabSheetStore: typeof import('./src/stores/tabSheet').useTabSheetStore
  const useTabsStore: typeof import('./src/stores/loaders/tabs').useTabsStore
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUserSheetStore: typeof import('./src/stores/ui/userSheet').useUserSheetStore
  const useUsersStore: typeof import('./src/stores/loaders/users').useUsersStore
  const useVueTable: typeof import('@tanstack/vue-table').useVueTable
  const userTabsQuery: typeof import('./src/services/supabase/queries/tabQueries').userTabsQuery
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { CreateNewDrink, EditDrink, DeleteDrink } from './src/interfaces/DrinkInterfaces'
  import('./src/interfaces/DrinkInterfaces')
  // @ts-ignore
  export type { TabStatus, CreateNewTab, Tab, EditTab, DeleteTab, AddTabItem, UpdateTabStatus, TabSummary } from './src/interfaces/TabInterfaces'
  import('./src/interfaces/TabInterfaces')
  // @ts-ignore
  export type { CreateNewUser, EditUser, DeleteUser } from './src/interfaces/UserInterfaces'
  import('./src/interfaces/UserInterfaces')
  // @ts-ignore
  export type { TabTotals } from './src/utils/tabCalculations'
  import('./src/utils/tabCalculations')
  // @ts-ignore
  export type { MenuInjectionOptions } from './src/providers/injectionKeys'
  import('./src/providers/injectionKeys')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly FlexRender: UnwrapRef<typeof import('@tanstack/vue-table')['FlexRender']>
    readonly RouterLink: UnwrapRef<typeof import('vue-router')['RouterLink']>
    readonly VAT_RATE: UnwrapRef<typeof import('./src/utils/tabCalculations')['VAT_RATE']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly addTabItemQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['addTabItemQuery']>
    readonly barApi: UnwrapRef<typeof import('./src/services/api/barApi')['default']>
    readonly barByIdQuery: UnwrapRef<typeof import('./src/services/supabase/queries/barQueries')['barByIdQuery']>
    readonly barQuery: UnwrapRef<typeof import('./src/services/supabase/queries/barQueries')['barQuery']>
    readonly barsQuery: UnwrapRef<typeof import('./src/services/supabase/queries/barQueries')['barsQuery']>
    readonly calculateTabTotals: UnwrapRef<typeof import('./src/utils/tabCalculations')['calculateTabTotals']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createTabPaymentQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['createTabPaymentQuery']>
    readonly createTabQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['createTabQuery']>
    readonly createTabSplitQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['createTabSplitQuery']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly deleteDrinkQuery: UnwrapRef<typeof import('./src/services/supabase/queries/drinkQueries')['deleteDrinkQuery']>
    readonly deleteTabItemQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['deleteTabItemQuery']>
    readonly deleteTabSplitQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['deleteTabSplitQuery']>
    readonly drinkApi: UnwrapRef<typeof import('./src/services/api/drinkApi')['default']>
    readonly drinkQuery: UnwrapRef<typeof import('./src/services/supabase/queries/drinkQueries')['drinkQuery']>
    readonly drinksByCategoryQuery: UnwrapRef<typeof import('./src/services/supabase/queries/drinkQueries')['drinksByCategoryQuery']>
    readonly drinksQuery: UnwrapRef<typeof import('./src/services/supabase/queries/drinkQueries')['drinksQuery']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly fetchDrinks: UnwrapRef<typeof import('./src/services/supabase/queries/drinkQueries')['fetchDrinks']>
    readonly formatCurrency: UnwrapRef<typeof import('./src/utils/currency')['formatCurrency']>
    readonly getCoreRowModel: UnwrapRef<typeof import('@tanstack/vue-table')['getCoreRowModel']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getPaginationRowModel: UnwrapRef<typeof import('@tanstack/vue-table')['getPaginationRowModel']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly menuApi: UnwrapRef<typeof import('./src/services/api/menuApi')['default']>
    readonly menuKey: UnwrapRef<typeof import('./src/providers/injectionKeys')['menuKey']>
    readonly menuQuery: UnwrapRef<typeof import('./src/services/supabase/queries/menuQueries')['menuQuery']>
    readonly menusQuery: UnwrapRef<typeof import('./src/services/supabase/queries/menuQueries')['menusQuery']>
    readonly menusWithCategoriesQuery: UnwrapRef<typeof import('./src/services/supabase/queries/menuQueries')['menusWithCategoriesQuery']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly openTabsQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['openTabsQuery']>
    readonly profileApi: UnwrapRef<typeof import('./src/services/api/profileApi')['default']>
    readonly profileQuery: UnwrapRef<typeof import('./src/services/supabase/queries/profileQueries')['profileQuery']>
    readonly profilesQuery: UnwrapRef<typeof import('./src/services/supabase/queries/profileQueries')['profilesQuery']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly socket: UnwrapRef<typeof import('./src/services/socket/socket')['socket']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly supabase: UnwrapRef<typeof import('./src/providers/supabaseClient')['supabase']>
    readonly tabApi: UnwrapRef<typeof import('./src/services/api/tabApi')['default']>
    readonly tabItemsQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['tabItemsQuery']>
    readonly tabPaymentsQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['tabPaymentsQuery']>
    readonly tabQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['tabQuery']>
    readonly tabSplitsQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['tabSplitsQuery']>
    readonly tabTotalsQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['tabTotalsQuery']>
    readonly tabsQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['tabsQuery']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly todaysTabsCountQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['todaysTabsCountQuery']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateDrinkQuery: UnwrapRef<typeof import('./src/services/supabase/queries/drinkQueries')['updateDrinkQuery']>
    readonly updateTabItemQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['updateTabItemQuery']>
    readonly updateTabQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['updateTabQuery']>
    readonly updateTabSplitQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['updateTabSplitQuery']>
    readonly updateUserQuery: UnwrapRef<typeof import('./src/services/supabase/queries/profileQueries')['updateUserQuery']>
    readonly useAddToTabStore: UnwrapRef<typeof import('./src/stores/ui/addToTab')['useAddToTabStore']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('./src/stores/auth')['useAuthStore']>
    readonly useBarsStore: UnwrapRef<typeof import('./src/stores/loaders/bars')['useBarsStore']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDrinkSheetStore: UnwrapRef<typeof import('./src/stores/ui/drinkSheet')['useDrinkSheetStore']>
    readonly useDrinksStore: UnwrapRef<typeof import('./src/stores/loaders/drinks')['useDrinksStore']>
    readonly useErrorStore: UnwrapRef<typeof import('./src/stores/error')['useErrorStore']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useMemoize: UnwrapRef<typeof import('@vueuse/core')['useMemoize']>
    readonly useMenusStore: UnwrapRef<typeof import('./src/stores/loaders/menus')['useMenusStore']>
    readonly useMeta: UnwrapRef<typeof import('vue-meta')['useMeta']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNewTabSheetStore: UnwrapRef<typeof import('./src/stores/ui/newTabSheet')['useNewTabSheetStore']>
    readonly usePageStore: UnwrapRef<typeof import('./src/stores/page')['usePageStore']>
    readonly usePaginationStore: UnwrapRef<typeof import('./src/stores/ui/pagination')['usePaginationStore']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSplitBillSheetStore: UnwrapRef<typeof import('./src/stores/ui/splitBillSheet')['useSplitBillSheetStore']>
    readonly useTabSheetStore: UnwrapRef<typeof import('./src/stores/tabSheet')['useTabSheetStore']>
    readonly useTabsStore: UnwrapRef<typeof import('./src/stores/loaders/tabs')['useTabsStore']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useUserSheetStore: UnwrapRef<typeof import('./src/stores/ui/userSheet')['useUserSheetStore']>
    readonly useUsersStore: UnwrapRef<typeof import('./src/stores/loaders/users')['useUsersStore']>
    readonly useVueTable: UnwrapRef<typeof import('@tanstack/vue-table')['useVueTable']>
    readonly userTabsQuery: UnwrapRef<typeof import('./src/services/supabase/queries/tabQueries')['userTabsQuery']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}