/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const barApi: typeof import('./src/services/api/barApi').default
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const drinkApi: typeof import('./src/services/api/drinkApi').default
  const effectScope: typeof import('vue').effectScope
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const menuApi: typeof import('./src/services/api/menuApi').default
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const profileApi: typeof import('./src/services/api/profileApi').default
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const tabApi: typeof import('./src/services/api/tabApi').default
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAddToTabStore: typeof import('./src/stores/ui/addToTab').useAddToTabStore
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./src/stores/auth').useAuthStore
  const useBarsStore: typeof import('./src/stores/loaders/bars').useBarsStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDrinkSheetStore: typeof import('./src/stores/ui/drinkSheet').useDrinkSheetStore
  const useDrinksStore: typeof import('./src/stores/loaders/drinks').useDrinksStore
  const useErrorStore: typeof import('./src/stores/error').useErrorStore
  const useId: typeof import('vue').useId
  const useMenusStore: typeof import('./src/stores/loaders/menus').useMenusStore
  const useMeta: typeof import('vue-meta').useMeta
  const useModel: typeof import('vue').useModel
  const useNewTabSheetStore: typeof import('./src/stores/ui/newTabSheet').useNewTabSheetStore
  const usePageStore: typeof import('./src/stores/page').usePageStore
  const usePaginationStore: typeof import('./src/stores/ui/pagination').usePaginationStore
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useSplitBillSheetStore: typeof import('./src/stores/ui/splitBillSheet').useSplitBillSheetStore
  const useTabSheetStore: typeof import('./src/stores/tabSheet').useTabSheetStore
  const useTabsStore: typeof import('./src/stores/loaders/tabs').useTabsStore
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUserSheetStore: typeof import('./src/stores/ui/userSheet').useUserSheetStore
  const useUsersStore: typeof import('./src/stores/loaders/users').useUsersStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { CreateNewDrink, EditDrink, DeleteDrink } from './src/interfaces/DrinkInterfaces'
  import('./src/interfaces/DrinkInterfaces')
  // @ts-ignore
  export type { TabStatus, CreateNewTab, Tab, EditTab, DeleteTab, AddTabItem, UpdateTabStatus, TabSummary } from './src/interfaces/TabInterfaces'
  import('./src/interfaces/TabInterfaces')
  // @ts-ignore
  export type { CreateNewUser, EditUser, DeleteUser } from './src/interfaces/UserInterfaces'
  import('./src/interfaces/UserInterfaces')
}
