/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...catchAll]': RouteRecordInfo<
      '/[...catchAll]',
      '/:catchAll(.*)',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/bars/': RouteRecordInfo<
      '/bars/',
      '/bars',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bars/[slug]': RouteRecordInfo<
      '/bars/[slug]',
      '/bars/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/drinks/': RouteRecordInfo<
      '/drinks/',
      '/drinks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/drinks/[slug]': RouteRecordInfo<
      '/drinks/[slug]',
      '/drinks/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/food/': RouteRecordInfo<
      '/food/',
      '/food',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menus/': RouteRecordInfo<
      '/menus/',
      '/menus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menus/[slug]': RouteRecordInfo<
      '/menus/[slug]',
      '/menus/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/menus/drinks/[category]': RouteRecordInfo<
      '/menus/drinks/[category]',
      '/menus/drinks/:category',
      { category: ParamValue<true> },
      { category: ParamValue<false> },
      | never
    >,
    '/pay/[id]': RouteRecordInfo<
      '/pay/[id]',
      '/pay/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/pos-login': RouteRecordInfo<
      '/pos-login',
      '/pos-login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/[username]': RouteRecordInfo<
      '/users/[username]',
      '/users/:username',
      { username: ParamValue<true> },
      { username: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...catchAll].vue': {
      routes:
        | '/[...catchAll]'
      views:
        | never
    }
    'src/pages/bars/index.vue': {
      routes:
        | '/bars/'
      views:
        | never
    }
    'src/pages/bars/[slug].vue': {
      routes:
        | '/bars/[slug]'
      views:
        | never
    }
    'src/pages/drinks/index.vue': {
      routes:
        | '/drinks/'
      views:
        | never
    }
    'src/pages/drinks/[slug].vue': {
      routes:
        | '/drinks/[slug]'
      views:
        | never
    }
    'src/pages/food/index.vue': {
      routes:
        | '/food/'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/menus/index.vue': {
      routes:
        | '/menus/'
      views:
        | never
    }
    'src/pages/menus/[slug].vue': {
      routes:
        | '/menus/[slug]'
      views:
        | never
    }
    'src/pages/menus/drinks/[category].vue': {
      routes:
        | '/menus/drinks/[category]'
      views:
        | never
    }
    'src/pages/pay/[id].vue': {
      routes:
        | '/pay/[id]'
      views:
        | never
    }
    'src/pages/pos-login.vue': {
      routes:
        | '/pos-login'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
    }
    'src/pages/users/[username].vue': {
      routes:
        | '/users/[username]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
