DROP TABLE IF EXISTS public.menu;

CREATE TABLE public.menu(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  thumb_url text NULL,
  active boolean NOT NULL DEFAULT TRUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT menu_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_menu_name ON public.menu(name);

DROP TABLE IF EXISTS public.menu_item_category;

CREATE TABLE public.menu_item_category(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  thumb_url text NULL,
  active boolean NOT NULL DEFAULT TRUE,
  menu text REFERENCES menu(name) NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT menu_item_category_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_menu_item_category_name ON public.menu_item_category(name);

DROP TABLE IF EXISTS public.drinks_glass;

CREATE TABLE public.drinks_glass(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  thumb_url text NULL,
  active boolean NOT NULL DEFAULT TRUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT drinks_glass_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_drinks_glass_name ON public.drinks_glass(name);

DROP TABLE IF EXISTS public.menu_item_ingredient;

CREATE TABLE public.menu_item_ingredient(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  thumb_url text NULL,
  active boolean NOT NULL DEFAULT TRUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT menu_item_ingredient_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_menu_item_ingredient_name ON public.menu_item_ingredient(name);

CREATE TABLE public.menu_item(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  category text REFERENCES menu_item_category(name) NOT NULL,
  alcoholic boolean DEFAULT NULL,
  glass text REFERENCES drinks_glass(name) NULL,
  instructions text NULL,
  thumb_url text NOT NULL,
  measurements text[] DEFAULT NULL,
  ingredients text[] DEFAULT NULL,
  active boolean NOT NULL DEFAULT FALSE,
  price numeric(6, 2) DEFAULT NULL,
  last_modified timestamp with time zone NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT menu_item_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_menu_item_category ON public.menu_item(category);

CREATE INDEX idx_menu_item_price ON public.menu_item(price);

