DROP TABLE IF EXISTS public.bar;

CREATE TABLE public.bar(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  thumb_url text NULL,
  CONSTRAINT bar_pkey PRIMARY KEY (id)
);

